# Generated by Django 4.0.4 on 2022-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('hot', 'Hot'), ('sale', 'Sale'), ('', 'Defalt')], max_length=100),
        ),
    ]
